### ISSUE TITLE
Error with some file

### ISSUE THREAD

**Issue by darachm** [darachm/PyFitSeq#8]
As run by Kieran, then reported this error:

python3 /opt/homebrew/lib/python3.9/site-packages/fitseq/fitseq.py \
--input /Users/kierancollins/Desktop/data/data2/starcode/216c.csv \
  --processes 8 \
--t-seq 0 3 5 7 \
  --min-iter 10 \
  --max-iter-num 100 \
  --min-step 0.001 \
  --output-mean-fitness 216mean.csv \
-o 216test.csv
Estimating Malthusian fitness for 4343 lineages...
-- Estimating initial guesses of global parameters
 0%|                                                       | 0/4343 [00:00<?, ?it/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████████| 4343/4343 [00:00<00:00, 9281.03it/s]
-- Optimizing fitness for every lineage with global parms
100%|█████████████████████████████████████████████████████████████████████████████████████████████| 4343/4343 [00:00<00:00, 1416915.24it/s]
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
 File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 125, in worker
  result = (True, func(*args, **kwds))
 File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 51, in starmapstar
  return list(itertools.starmap(args[0], args[1]))
 File "/opt/homebrew/lib/python3.9/site-packages/fitseq/fitseq.py", line 292, in fun_x_est_lineage
  x0=x0_global[i],
TypeError: 'NoneType' object is not subscriptable
"""
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
 File "/opt/homebrew/lib/python3.9/site-packages/fitseq/fitseq.py", line 570, in <module>
  main()
 File "/opt/homebrew/lib/python3.9/site-packages/fitseq/fitseq.py", line 464, in main
  pool_obj.starmap(
 File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 372, in starmap
  return self._map_async(func, iterable, starmapstar, chunksize).get()
 File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 771, in get
  raise self._value

**Comment by darachm** [comment]
Un able to reproduce this error
